# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def development_pods
    # If you're using Xcode 7 / Swift 2.0
    pod 'Alamofire', '~> 3.0'
    pod 'SwiftyJSON', '~> 2.3'
    pod 'ChameleonFramework', '~> 2.0'
    pod 'pop', '~> 1.0'
    pod 'BubbleTransition', '~> 1.0'
    pod 'AMPopTip', '~> 0.9'
    pod 'AMWaveTransition', '~> 0.6'
    pod 'AHKActionSheet', '~> 0.5'
    pod 'Parse', '~> 1.9'
    pod 'Eureka', '~> 1.0'
end

target 'BusyBuy' do
    development_pods
end

target 'BusyBuyTests' do
end

target 'BusyBuyUITests' do
end
